//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraspIT_EEG.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string R2D2ComPort {
            get {
                return ((string)(this["R2D2ComPort"]));
            }
            set {
                this["R2D2ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\ProgramData\\\\Emotiv\\\\")]
        public string EmotivUserFilePath {
            get {
                return ((string)(this["EmotivUserFilePath"]));
            }
            set {
                this["EmotivUserFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4711")]
        public int VendorID {
            get {
                return ((int)(this["VendorID"]));
            }
            set {
                this["VendorID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProductID {
            get {
                return ((int)(this["ProductID"]));
            }
            set {
                this["ProductID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ArmID {
            get {
                return ((int)(this["ArmID"]));
            }
            set {
                this["ArmID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.22698672")]
        public double Frequency1gain {
            get {
                return ((double)(this["Frequency1gain"]));
            }
            set {
                this["Frequency1gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6642317127")]
        public double Frequency1coef1 {
            get {
                return ((double)(this["Frequency1coef1"]));
            }
            set {
                this["Frequency1coef1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2500608525")]
        public double Frequency1coef2 {
            get {
                return ((double)(this["Frequency1coef2"]));
            }
            set {
                this["Frequency1coef2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2.2141423193")]
        public double Frequency1coef3 {
            get {
                return ((double)(this["Frequency1coef3"]));
            }
            set {
                this["Frequency1coef3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.6015694459")]
        public double Frequency1coef4 {
            get {
                return ((double)(this["Frequency1coef4"]));
            }
            set {
                this["Frequency1coef4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5249625592")]
        public double Frequency1coef5 {
            get {
                return ((double)(this["Frequency1coef5"]));
            }
            set {
                this["Frequency1coef5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3764534782")]
        public double Frequency1coef6 {
            get {
                return ((double)(this["Frequency1coef6"]));
            }
            set {
                this["Frequency1coef6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.22698672")]
        public double Frequency2gain {
            get {
                return ((double)(this["Frequency2gain"]));
            }
            set {
                this["Frequency2gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6642317127")]
        public double Frequency2coef1 {
            get {
                return ((double)(this["Frequency2coef1"]));
            }
            set {
                this["Frequency2coef1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2500608525")]
        public double Frequency2coef2 {
            get {
                return ((double)(this["Frequency2coef2"]));
            }
            set {
                this["Frequency2coef2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2.2141423193")]
        public double Frequency2coef3 {
            get {
                return ((double)(this["Frequency2coef3"]));
            }
            set {
                this["Frequency2coef3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.6015694459")]
        public double Frequency2coef4 {
            get {
                return ((double)(this["Frequency2coef4"]));
            }
            set {
                this["Frequency2coef4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5249625592")]
        public double Frequency2coef5 {
            get {
                return ((double)(this["Frequency2coef5"]));
            }
            set {
                this["Frequency2coef5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3764534782")]
        public double Frequency2coef6 {
            get {
                return ((double)(this["Frequency2coef6"]));
            }
            set {
                this["Frequency2coef6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.22698672")]
        public double Frequency3gain {
            get {
                return ((double)(this["Frequency3gain"]));
            }
            set {
                this["Frequency3gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6642317127")]
        public double Frequency3coef1 {
            get {
                return ((double)(this["Frequency3coef1"]));
            }
            set {
                this["Frequency3coef1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2500608525")]
        public double Frequency3coef2 {
            get {
                return ((double)(this["Frequency3coef2"]));
            }
            set {
                this["Frequency3coef2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2.2141423193")]
        public double Frequency3coef3 {
            get {
                return ((double)(this["Frequency3coef3"]));
            }
            set {
                this["Frequency3coef3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.6015694459")]
        public double Frequency3coef4 {
            get {
                return ((double)(this["Frequency3coef4"]));
            }
            set {
                this["Frequency3coef4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5249625592")]
        public double Frequency3coef5 {
            get {
                return ((double)(this["Frequency3coef5"]));
            }
            set {
                this["Frequency3coef5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3764534782")]
        public double Frequency3coef6 {
            get {
                return ((double)(this["Frequency3coef6"]));
            }
            set {
                this["Frequency3coef6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.22698672")]
        public double Frequency4gain {
            get {
                return ((double)(this["Frequency4gain"]));
            }
            set {
                this["Frequency4gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6642317127")]
        public double Frequency4coef1 {
            get {
                return ((double)(this["Frequency4coef1"]));
            }
            set {
                this["Frequency4coef1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2500608525")]
        public double Frequency4coef2 {
            get {
                return ((double)(this["Frequency4coef2"]));
            }
            set {
                this["Frequency4coef2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2.2141423193")]
        public double Frequency4coef3 {
            get {
                return ((double)(this["Frequency4coef3"]));
            }
            set {
                this["Frequency4coef3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.6015694459")]
        public double Frequency4coef4 {
            get {
                return ((double)(this["Frequency4coef4"]));
            }
            set {
                this["Frequency4coef4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5249625592")]
        public double Frequency4coef5 {
            get {
                return ((double)(this["Frequency4coef5"]));
            }
            set {
                this["Frequency4coef5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3764534782")]
        public double Frequency4coef6 {
            get {
                return ((double)(this["Frequency4coef6"]));
            }
            set {
                this["Frequency4coef6"] = value;
            }
        }
    }
}
