//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraspIT_EEG.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string R2D2ComPort {
            get {
                return ((string)(this["R2D2ComPort"]));
            }
            set {
                this["R2D2ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\ProgramData\\\\Emotiv\\\\")]
        public string EmotivUserFilePath {
            get {
                return ((string)(this["EmotivUserFilePath"]));
            }
            set {
                this["EmotivUserFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4711")]
        public int VendorID {
            get {
                return ((int)(this["VendorID"]));
            }
            set {
                this["VendorID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProductID {
            get {
                return ((int)(this["ProductID"]));
            }
            set {
                this["ProductID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ArmID {
            get {
                return ((int)(this["ArmID"]));
            }
            set {
                this["ArmID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70996.86298")]
        public double Bandpass6_7gain {
            get {
                return ((double)(this["Bandpass6_7gain"]));
            }
            set {
                this["Bandpass6_7gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.9064815219")]
        public double Bandpass6_7coef1 {
            get {
                return ((double)(this["Bandpass6_7coef1"]));
            }
            set {
                this["Bandpass6_7coef1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.2504533221")]
        public double Bandpass6_7coef2 {
            get {
                return ((double)(this["Bandpass6_7coef2"]));
            }
            set {
                this["Bandpass6_7coef2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-12.9468830643")]
        public double Bandpass6_7coef3 {
            get {
                return ((double)(this["Bandpass6_7coef3"]));
            }
            set {
                this["Bandpass6_7coef3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17.3739583958")]
        public double Bandpass6_7coef4 {
            get {
                return ((double)(this["Bandpass6_7coef4"]));
            }
            set {
                this["Bandpass6_7coef4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-13.3776569031")]
        public double Bandpass6_7coef5 {
            get {
                return ((double)(this["Bandpass6_7coef5"]));
            }
            set {
                this["Bandpass6_7coef5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.6056470274")]
        public double Bandpass6_7coef6 {
            get {
                return ((double)(this["Bandpass6_7coef6"]));
            }
            set {
                this["Bandpass6_7coef6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70996.86304")]
        public double Bandpass7_8gain {
            get {
                return ((double)(this["Bandpass7_8gain"]));
            }
            set {
                this["Bandpass7_8gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.9064815219")]
        public double Bandpass7_8coef1 {
            get {
                return ((double)(this["Bandpass7_8coef1"]));
            }
            set {
                this["Bandpass7_8coef1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.15902028")]
        public double Bandpass7_8coef2 {
            get {
                return ((double)(this["Bandpass7_8coef2"]));
            }
            set {
                this["Bandpass7_8coef2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-12.5968492018")]
        public double Bandpass7_8coef3 {
            get {
                return ((double)(this["Bandpass7_8coef3"]));
            }
            set {
                this["Bandpass7_8coef3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16.8499943409")]
        public double Bandpass7_8coef4 {
            get {
                return ((double)(this["Bandpass7_8coef4"]));
            }
            set {
                this["Bandpass7_8coef4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-13.0159752844")]
        public double Bandpass7_8coef5 {
            get {
                return ((double)(this["Bandpass7_8coef5"]));
            }
            set {
                this["Bandpass7_8coef5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.5080285307")]
        public double Bandpass7_8coef6 {
            get {
                return ((double)(this["Bandpass7_8coef6"]));
            }
            set {
                this["Bandpass7_8coef6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70996.86306")]
        public double Bandpass8_9gain {
            get {
                return ((double)(this["Bandpass8_9gain"]));
            }
            set {
                this["Bandpass8_9gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.9064815219")]
        public double Bandpass8_9coef1 {
            get {
                return ((double)(this["Bandpass8_9coef1"]));
            }
            set {
                this["Bandpass8_9coef1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.0551587062")]
        public double Bandpass8_9coef2 {
            get {
                return ((double)(this["Bandpass8_9coef2"]));
            }
            set {
                this["Bandpass8_9coef2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-12.2066948229")]
        public double Bandpass8_9coef3 {
            get {
                return ((double)(this["Bandpass8_9coef3"]));
            }
            set {
                this["Bandpass8_9coef3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16.2689518805")]
        public double Bandpass8_9coef4 {
            get {
                return ((double)(this["Bandpass8_9coef4"]));
            }
            set {
                this["Bandpass8_9coef4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-12.6128380955")]
        public double Bandpass8_9coef5 {
            get {
                return ((double)(this["Bandpass8_9coef5"]));
            }
            set {
                this["Bandpass8_9coef5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.3971407108")]
        public double Bandpass8_9coef6 {
            get {
                return ((double)(this["Bandpass8_9coef6"]));
            }
            set {
                this["Bandpass8_9coef6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9304.588516")]
        public double Bandpass9_11gain {
            get {
                return ((double)(this["Bandpass9_11gain"]));
            }
            set {
                this["Bandpass9_11gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.821660008")]
        public double Bandpass9_11coef1 {
            get {
                return ((double)(this["Bandpass9_11coef1"]));
            }
            set {
                this["Bandpass9_11coef1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.4954776676")]
        public double Bandpass9_11coef2 {
            get {
                return ((double)(this["Bandpass9_11coef2"]));
            }
            set {
                this["Bandpass9_11coef2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10.8292354227")]
        public double Bandpass9_11coef3 {
            get {
                return ((double)(this["Bandpass9_11coef3"]));
            }
            set {
                this["Bandpass9_11coef3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14.5814195235")]
        public double Bandpass9_11coef4 {
            get {
                return ((double)(this["Bandpass9_11coef4"]));
            }
            set {
                this["Bandpass9_11coef4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-11.562225122")]
        public double Bandpass9_11coef5 {
            get {
                return ((double)(this["Bandpass9_11coef5"]));
            }
            set {
                this["Bandpass9_11coef5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.1246045354")]
        public double Bandpass9_11coef6 {
            get {
                return ((double)(this["Bandpass9_11coef6"]));
            }
            set {
                this["Bandpass9_11coef6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9304.588548")]
        public double Bandpass11_13gain {
            get {
                return ((double)(this["Bandpass11_13gain"]));
            }
            set {
                this["Bandpass11_13gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.821660008")]
        public double Bandpass11_13coef1 {
            get {
                return ((double)(this["Bandpass11_13coef1"]));
            }
            set {
                this["Bandpass11_13coef1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.238307006")]
        public double Bandpass11_13coef2 {
            get {
                return ((double)(this["Bandpass11_13coef2"]));
            }
            set {
                this["Bandpass11_13coef2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-9.9175516295")]
        public double Bandpass11_13coef3 {
            get {
                return ((double)(this["Bandpass11_13coef3"]));
            }
            set {
                this["Bandpass11_13coef3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13.2241672905")]
        public double Bandpass11_13coef4 {
            get {
                return ((double)(this["Bandpass11_13coef4"]));
            }
            set {
                this["Bandpass11_13coef4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10.5888017443")]
        public double Bandpass11_13coef5 {
            get {
                return ((double)(this["Bandpass11_13coef5"]));
            }
            set {
                this["Bandpass11_13coef5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.8314437111")]
        public double Bandpass11_13coef6 {
            get {
                return ((double)(this["Bandpass11_13coef6"]));
            }
            set {
                this["Bandpass11_13coef6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9304.588558")]
        public double Bandpass14_16gain {
            get {
                return ((double)(this["Bandpass14_16gain"]));
            }
            set {
                this["Bandpass14_16gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.821660008")]
        public double Bandpass14_16coef1 {
            get {
                return ((double)(this["Bandpass14_16coef1"]));
            }
            set {
                this["Bandpass14_16coef1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.7769009224")]
        public double Bandpass14_16coef2 {
            get {
                return ((double)(this["Bandpass14_16coef2"]));
            }
            set {
                this["Bandpass14_16coef2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-8.4164211561")]
        public double Bandpass14_16coef3 {
            get {
                return ((double)(this["Bandpass14_16coef3"]));
            }
            set {
                this["Bandpass14_16coef3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11.0169678703")]
        public double Bandpass14_16coef4 {
            get {
                return ((double)(this["Bandpass14_16coef4"]));
            }
            set {
                this["Bandpass14_16coef4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-8.9860141257")]
        public double Bandpass14_16coef5 {
            get {
                return ((double)(this["Bandpass14_16coef5"]));
            }
            set {
                this["Bandpass14_16coef5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.3054654095")]
        public double Bandpass14_16coef6 {
            get {
                return ((double)(this["Bandpass14_16coef6"]));
            }
            set {
                this["Bandpass14_16coef6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9304.588559")]
        public double Bandpass19_21gain {
            get {
                return ((double)(this["Bandpass19_21gain"]));
            }
            set {
                this["Bandpass19_21gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.821660008")]
        public double Bandpass19_21coef1 {
            get {
                return ((double)(this["Bandpass19_21coef1"]));
            }
            set {
                this["Bandpass19_21coef1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.8319462023")]
        public double Bandpass19_21coef2 {
            get {
                return ((double)(this["Bandpass19_21coef2"]));
            }
            set {
                this["Bandpass19_21coef2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5.8815433063")]
        public double Bandpass19_21coef3 {
            get {
                return ((double)(this["Bandpass19_21coef3"]));
            }
            set {
                this["Bandpass19_21coef3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7.2887686977")]
        public double Bandpass19_21coef4 {
            get {
                return ((double)(this["Bandpass19_21coef4"]));
            }
            set {
                this["Bandpass19_21coef4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-6.2794733524")]
        public double Bandpass19_21coef5 {
            get {
                return ((double)(this["Bandpass19_21coef5"]));
            }
            set {
                this["Bandpass19_21coef5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.228267478")]
        public double Bandpass19_21coef6 {
            get {
                return ((double)(this["Bandpass19_21coef6"]));
            }
            set {
                this["Bandpass19_21coef6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.226986718")]
        public double Bandpass0_16_60gain {
            get {
                return ((double)(this["Bandpass0_16_60gain"]));
            }
            set {
                this["Bandpass0_16_60gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6642317127")]
        public double Bandpass0_16_60coef1 {
            get {
                return ((double)(this["Bandpass0_16_60coef1"]));
            }
            set {
                this["Bandpass0_16_60coef1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2500608525")]
        public double Bandpass0_16_60coef2 {
            get {
                return ((double)(this["Bandpass0_16_60coef2"]));
            }
            set {
                this["Bandpass0_16_60coef2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2.2141423193")]
        public double Bandpass0_16_60coef3 {
            get {
                return ((double)(this["Bandpass0_16_60coef3"]));
            }
            set {
                this["Bandpass0_16_60coef3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.6015694459")]
        public double Bandpass0_16_60coef4 {
            get {
                return ((double)(this["Bandpass0_16_60coef4"]));
            }
            set {
                this["Bandpass0_16_60coef4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5249625592")]
        public double Bandpass0_16_60coef5 {
            get {
                return ((double)(this["Bandpass0_16_60coef5"]));
            }
            set {
                this["Bandpass0_16_60coef5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3764534782")]
        public double Bandpass0_16_60coef6 {
            get {
                return ((double)(this["Bandpass0_16_60coef6"]));
            }
            set {
                this["Bandpass0_16_60coef6"] = value;
            }
        }
    }
}
